/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-09-16 16:01:30 UTC)
 * on 2013-09-24 at 17:41:38 UTC 
 * Modify at your own risk.
 */

package com.appspot.demos_biira.birra;

/**
 * Service definition for Birra (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link BirraRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Birra extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the birra library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://demos-biira.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "birra/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Birra(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Birra(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getBeer".
   *
   * This request holds the parameters needed by the the birra server.  After setting any optional
   * parameters, call the {@link GetBeer#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetBeer getBeer(java.lang.Long id) throws java.io.IOException {
    GetBeer result = new GetBeer(id);
    initialize(result);
    return result;
  }

  public class GetBeer extends BirraRequest<com.appspot.demos_biira.birra.model.Beer> {

    private static final String REST_PATH = "beer/{id}";

    /**
     * Create a request for the method "getBeer".
     *
     * This request holds the parameters needed by the the birra server.  After setting any optional
     * parameters, call the {@link GetBeer#execute()} method to invoke the remote operation. <p>
     * {@link
     * GetBeer#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetBeer(java.lang.Long id) {
      super(Birra.this, "GET", REST_PATH, null, com.appspot.demos_biira.birra.model.Beer.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetBeer setAlt(java.lang.String alt) {
      return (GetBeer) super.setAlt(alt);
    }

    @Override
    public GetBeer setFields(java.lang.String fields) {
      return (GetBeer) super.setFields(fields);
    }

    @Override
    public GetBeer setKey(java.lang.String key) {
      return (GetBeer) super.setKey(key);
    }

    @Override
    public GetBeer setOauthToken(java.lang.String oauthToken) {
      return (GetBeer) super.setOauthToken(oauthToken);
    }

    @Override
    public GetBeer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetBeer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetBeer setQuotaUser(java.lang.String quotaUser) {
      return (GetBeer) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetBeer setUserIp(java.lang.String userIp) {
      return (GetBeer) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetBeer setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetBeer set(String parameterName, Object value) {
      return (GetBeer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertBeer".
   *
   * This request holds the parameters needed by the the birra server.  After setting any optional
   * parameters, call the {@link InsertBeer#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.demos_biira.birra.model.Beer}
   * @return the request
   */
  public InsertBeer insertBeer(com.appspot.demos_biira.birra.model.Beer content) throws java.io.IOException {
    InsertBeer result = new InsertBeer(content);
    initialize(result);
    return result;
  }

  public class InsertBeer extends BirraRequest<com.appspot.demos_biira.birra.model.Beer> {

    private static final String REST_PATH = "beer";

    /**
     * Create a request for the method "insertBeer".
     *
     * This request holds the parameters needed by the the birra server.  After setting any optional
     * parameters, call the {@link InsertBeer#execute()} method to invoke the remote operation. <p>
     * {@link
     * InsertBeer#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.demos_biira.birra.model.Beer}
     * @since 1.13
     */
    protected InsertBeer(com.appspot.demos_biira.birra.model.Beer content) {
      super(Birra.this, "POST", REST_PATH, content, com.appspot.demos_biira.birra.model.Beer.class);
    }

    @Override
    public InsertBeer setAlt(java.lang.String alt) {
      return (InsertBeer) super.setAlt(alt);
    }

    @Override
    public InsertBeer setFields(java.lang.String fields) {
      return (InsertBeer) super.setFields(fields);
    }

    @Override
    public InsertBeer setKey(java.lang.String key) {
      return (InsertBeer) super.setKey(key);
    }

    @Override
    public InsertBeer setOauthToken(java.lang.String oauthToken) {
      return (InsertBeer) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertBeer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertBeer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertBeer setQuotaUser(java.lang.String quotaUser) {
      return (InsertBeer) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertBeer setUserIp(java.lang.String userIp) {
      return (InsertBeer) super.setUserIp(userIp);
    }

    @Override
    public InsertBeer set(String parameterName, Object value) {
      return (InsertBeer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listBeer".
   *
   * This request holds the parameters needed by the the birra server.  After setting any optional
   * parameters, call the {@link ListBeer#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListBeer listBeer() throws java.io.IOException {
    ListBeer result = new ListBeer();
    initialize(result);
    return result;
  }

  public class ListBeer extends BirraRequest<com.appspot.demos_biira.birra.model.CollectionResponseBeer> {

    private static final String REST_PATH = "beer";

    /**
     * Create a request for the method "listBeer".
     *
     * This request holds the parameters needed by the the birra server.  After setting any optional
     * parameters, call the {@link ListBeer#execute()} method to invoke the remote operation. <p>
     * {@link
     * ListBeer#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListBeer() {
      super(Birra.this, "GET", REST_PATH, null, com.appspot.demos_biira.birra.model.CollectionResponseBeer.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListBeer setAlt(java.lang.String alt) {
      return (ListBeer) super.setAlt(alt);
    }

    @Override
    public ListBeer setFields(java.lang.String fields) {
      return (ListBeer) super.setFields(fields);
    }

    @Override
    public ListBeer setKey(java.lang.String key) {
      return (ListBeer) super.setKey(key);
    }

    @Override
    public ListBeer setOauthToken(java.lang.String oauthToken) {
      return (ListBeer) super.setOauthToken(oauthToken);
    }

    @Override
    public ListBeer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListBeer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListBeer setQuotaUser(java.lang.String quotaUser) {
      return (ListBeer) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListBeer setUserIp(java.lang.String userIp) {
      return (ListBeer) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListBeer setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListBeer setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListBeer set(String parameterName, Object value) {
      return (ListBeer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeBeer".
   *
   * This request holds the parameters needed by the the birra server.  After setting any optional
   * parameters, call the {@link RemoveBeer#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveBeer removeBeer(java.lang.Long id) throws java.io.IOException {
    RemoveBeer result = new RemoveBeer(id);
    initialize(result);
    return result;
  }

  public class RemoveBeer extends BirraRequest<Void> {

    private static final String REST_PATH = "beer/{id}";

    /**
     * Create a request for the method "removeBeer".
     *
     * This request holds the parameters needed by the the birra server.  After setting any optional
     * parameters, call the {@link RemoveBeer#execute()} method to invoke the remote operation. <p>
     * {@link
     * RemoveBeer#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveBeer(java.lang.Long id) {
      super(Birra.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveBeer setAlt(java.lang.String alt) {
      return (RemoveBeer) super.setAlt(alt);
    }

    @Override
    public RemoveBeer setFields(java.lang.String fields) {
      return (RemoveBeer) super.setFields(fields);
    }

    @Override
    public RemoveBeer setKey(java.lang.String key) {
      return (RemoveBeer) super.setKey(key);
    }

    @Override
    public RemoveBeer setOauthToken(java.lang.String oauthToken) {
      return (RemoveBeer) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveBeer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveBeer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveBeer setQuotaUser(java.lang.String quotaUser) {
      return (RemoveBeer) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveBeer setUserIp(java.lang.String userIp) {
      return (RemoveBeer) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveBeer setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveBeer set(String parameterName, Object value) {
      return (RemoveBeer) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateBeer".
   *
   * This request holds the parameters needed by the the birra server.  After setting any optional
   * parameters, call the {@link UpdateBeer#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.demos_biira.birra.model.Beer}
   * @return the request
   */
  public UpdateBeer updateBeer(com.appspot.demos_biira.birra.model.Beer content) throws java.io.IOException {
    UpdateBeer result = new UpdateBeer(content);
    initialize(result);
    return result;
  }

  public class UpdateBeer extends BirraRequest<com.appspot.demos_biira.birra.model.Beer> {

    private static final String REST_PATH = "beer";

    /**
     * Create a request for the method "updateBeer".
     *
     * This request holds the parameters needed by the the birra server.  After setting any optional
     * parameters, call the {@link UpdateBeer#execute()} method to invoke the remote operation. <p>
     * {@link
     * UpdateBeer#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.demos_biira.birra.model.Beer}
     * @since 1.13
     */
    protected UpdateBeer(com.appspot.demos_biira.birra.model.Beer content) {
      super(Birra.this, "PUT", REST_PATH, content, com.appspot.demos_biira.birra.model.Beer.class);
    }

    @Override
    public UpdateBeer setAlt(java.lang.String alt) {
      return (UpdateBeer) super.setAlt(alt);
    }

    @Override
    public UpdateBeer setFields(java.lang.String fields) {
      return (UpdateBeer) super.setFields(fields);
    }

    @Override
    public UpdateBeer setKey(java.lang.String key) {
      return (UpdateBeer) super.setKey(key);
    }

    @Override
    public UpdateBeer setOauthToken(java.lang.String oauthToken) {
      return (UpdateBeer) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateBeer setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateBeer) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateBeer setQuotaUser(java.lang.String quotaUser) {
      return (UpdateBeer) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateBeer setUserIp(java.lang.String userIp) {
      return (UpdateBeer) super.setUserIp(userIp);
    }

    @Override
    public UpdateBeer set(String parameterName, Object value) {
      return (UpdateBeer) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Birra}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Birra}. */
    @Override
    public Birra build() {
      return new Birra(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link BirraRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setBirraRequestInitializer(
        BirraRequestInitializer birraRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(birraRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
